### ISSUE TITLE
Images not saved in notebook

### ISSUE THREAD

**Issue by arthurl** [millejoh/emacs-ipython-notebook#78] opened 2015-12-14 10:25 UTC
Hi, I'm new to EIN so please excuse me if this is intended behaviour.

For some reason, EIN refuses to save images. EIN _does_ display the image correctly, it just refuses to save the image in the ipython file as a base64 blob.

To reproduce, open a fresh notebook and execute the code block below, and then save the ipython file. Afterwards, reopen the file.

``` python
%matplotlib inline
import matplotlib.pyplot as plt
from numpy import random
def plotnormal():
    return plt.plot (random.randn (1000), random.randn (1000), 'o', alpha=0.3)
plotnormal ()
```

Doing so on the browser interface displays the notebook with the plot as expected. Doing the same in EIN yields

```
In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
from numpy import random
def plotnormal():
    return plt.plot (random.randn (1000), random.randn (1000), 'o', alpha=0.3)
plotnormal ()
<matplotlib.figure.Figure at 0x10cc67438>
[<matplotlib.lines.Line2D at 0x10e044c18>]
```

with no image.

Looking at the ipynb file from the browser,

``` json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "autoscroll": "json-false",
    "collapsed": false,
    "ein.tags": [
     "worksheet-0"
    ]
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[<matplotlib.lines.Line2D at 0x1060ccb00>]"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "<huge base64 blob here>",
      "text/plain": [
       "<matplotlib.figure.Figure at 0x104cf2518>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "%matplotlib inline\n",
    "import matplotlib.pyplot as plt\n",
    "from numpy import random\n",
    "def plotnormal():\n",
    "    return plt.plot (random.randn (1000), random.randn (1000), 'o', alpha=0.3)\n",
    "plotnormal ()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.1"
  },
  "name": "plot-test-1.ipynb"
 },
 "nbformat": 4,
 "nbformat_minor": 0
}

```

Looking at the raw ipython file from EIN,

``` json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "autoscroll": "json-false",
    "collapsed": false,
    "ein.tags": [
     "worksheet-0"
    ]
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<matplotlib.figure.Figure at 0x10cc67438>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": [
       "[<matplotlib.lines.Line2D at 0x10e044c18>]"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "%matplotlib inline\n",
    "import matplotlib.pyplot as plt\n",
    "from numpy import random\n",
    "def plotnormal():\n",
    "    return plt.plot (random.randn (1000), random.randn (1000), 'o', alpha=0.3)\n",
    "plotnormal ()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.1"
  },
  "name": "plot-test.ipynb"
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
```

In particular, the base64 blob is missing.

**Comment by arthurl** [comment] 2015-12-14 10:25
## Check list

- [x] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [x] Does IPython works from the web browser?
- [x] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [x] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Description of the problem you have

Above.

## Steps to reproduce the problem

Above

## Expected output

Above

## Your EIN configuration (in .emacs.d/init.el or somewhere else)

``` eLisp
(require-package 'ein)

(setq-default ein:use-auto-complete t)
(setq-default ein:use-auto-complete-superpack t)

```

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`):

    4.0.1

2. How do you start IPython? (e.g., `ipython notebook --port 9999`):

    ipython notebook

3. What is your IPython notebook port number or URL?:

    8888

## Additional information (if any)


## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 24.5.1 (x86_64-apple-darwin15.2.0, Carbon Version 157 AppKit 1404.34)
 of 2015-12-11 on fsec.local"
 :emacs-bzr-version nil
 :window-system mac
 :emacs-variant nil
 :os
 (:uname
  "Darwin fsec.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
"
  :lsb-release nil)
 :image-types
 (svg image-io imagemagick png gif tiff jpeg xpm xbm pbm)
 :image-types-available
 (svg image-io imagemagick png gif tiff jpeg xpm xbm pbm)
 :request
 (:backend curl)
 :ein
 (:version "0.7"
           :source-dir "/Users/arthur/.emacs.d/elpa/ein-20150914.1116/")
 :lib
 ((:name "websocket"
         :path "~/.emacs.d/elpa/websocket-20150719.1048/websocket.elc"
         :featurep t
         :version-var websocket-version
         :version "1.5")
  (:name "request"
         :path "~/.emacs.d/elpa/request-20140316.417/request.elc"
         :featurep t
         :version-var request-version
         :version "0.2.0")
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-20151211.227/auto-complete.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "auto-complete"
         :path "~/.emacs.d/elpa/auto-complete-20151211.227/auto-complete.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "popup"
         :path "~/.emacs.d/elpa/popup-20151125.542/popup.elc"
         :featurep t
         :version-var popup-version
         :version "0.5.3")
  (:name "python"
         :path
         "/usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.14/share/emacs/24.5/lisp/progmodes/python.elc"
         :featurep t
         :version-var nil
         :version nil)
  (:name "markdown-mode"
         :path "~/.emacs.d/elpa/markdown-mode-20151206.816/markdown-mode.elc"
         :featurep t
         :version-var markdown-mode-version
         :version "2.0")))
```

**Comment by millejoh** [comment] 2015-12-15 22:00
Sadly you are correct that this is not the intended behavior. Note that ein will correctly load notebooks with plot images (try saving a notebook from the web interface and then load it into ein), but will not save images. I do mean to fix this, but the code for saving nbformat v4 files is an unholy mess of code, written during the witching hour while under the influence of the vapors from dirty diapers. It will take some work to fix, but I will see what I can do. Wish me luck.

**Comment by arthurl** [comment] 2015-12-17 10:51
I'll look forward to it. Good luck with that, and thanks for the great work!

**Comment by millejoh** [comment] 2015-12-22 18:53
Looks like you are following melpa-stable, but if you are feeling adventurous my latest commit (a4ab2a52f5ed4daa2b1c108cc5b88350a97a0805) tries to fix this.I am going to work with this for a while before merging with main to make sure nothing else is horribly broken.

**Comment by cjauvin** [comment] 2016-01-05 17:27
I just discovered `ein` yesterday, and I have been simply in complete awe since then.. many, many thanks for this superb plugin, which changes everything for me! I just stumbled upon the issue mentioned in this thread though, while trying to upload a notebook to GitHub (to have it rendered there), so I'll be sure to give your latest work a shot.

**Comment by cjauvin** [comment] 2016-01-05 17:39
I'm wondering if there's a special `use-package` trick, to force the use of your particular fix branch?

**Comment by millejoh** [comment] 2016-01-06 14:49
You would have to checkout that particular branch from github to your machin and set up emacs accordingly. But have no fear! I finally merged my updates into the master branch and pushed them to github. The melpa developmental branch should be updating soon, should you should be able to download/update from Emacs's package manager today. If no one finds anything horribly wrong I will tag this latest commit so melpa stable can also get the updates.

Good luck!

**Comment by cjauvin** [comment] 2016-01-06 16:29
I have updated through melpa (now running `20160105.1535`) and I first noticed that there was a problem with `cl-generic`. I installed it manually, and it seems to have solved it.

However when I tried to produce a notebook with raw images embedded, I did not succeed:

https://gist.github.com/cjauvin/2da0437f959f773ee8f5

Do I have something wrong?

**Comment by cjauvin** [comment] 2016-01-06 16:34
Another small issue: I was using `ein:notebook-mode-map` in the previous version to unbind certain keyboard shortcuts, but it seems to have disappeared from this latest update. Would there be an easy way to achieve the same result?

**Comment by millejoh** [comment] 2016-01-07 13:05
You did nothing wrong, it was me. So - one more time around the block. Just pushed another commit; let me know how it works. The cl-generic issue may be because I am working with emacs 25.1 so some cl-generic stuff may have snuck in by accident. I think eventually all the ewoc code will need to be updated to use cl-generic eventually.

Where are you setting `ein:notebook-mode-map`? When melpa downloads an update it recompiles all the files. That may be why you are seeing your changes disappear.

**Comment by cjauvin** [comment] 2016-01-07 15:07
Your update doesn't seem to be available in melpa yet:

https://melpa.org/#/ein

I'm using `ein:notebook-mode-map` simply to unbind two key shortcuts which I use for something else:

    ;; in init.el
    (use-package ein
      :ensure t
      :config (unbind-key "M-<up>" ein:notebook-mode-map)
              (unbind-key "M-<down>" ein:notebook-mode-map))

This was working prior to version `20160105.1535`, but now it yields this error at startup:

    Error (use-package): ein :config: Symbol's value as variable is void: ein:notebook-mode-map

**Comment by millejoh** [comment] 2016-01-07 16:37
It may take up to a day for MELPA to update - I'm not sure how often their update scripts run. I will take a look at the mode-map issue. It's not something I do in my setup so it is very possible I broke this functionality somewhere along the way without realizing it.

**Comment by cjauvin** [comment] 2016-01-07 16:40
Good news, melpa has updated and it now seems to work very well!

https://gist.github.com/cjauvin/32b5f3122b7266f86869

Thanks a lot for the great support and communication!

**Comment by millejoh** [comment] 2016-01-15 04:16
Great! I am going to open a new issue for the mode-map problem.

**Closed by millejoh** 2016-01-15 04:16 UTC

**Comment by jcpetkovich** [comment] 2017-06-07 23:39
This seems to be happening to me with the current version of `ein`. I can reproduce it with the same snippet. It seems to have started with a recent update, I don't have time to bisect this right now, but I will try to this weekend.
