### ISSUE TITLE
EIN markdown cells cause emacs to freeze, CPU high use

### ISSUE THREAD

**Issue by vv111y** [millejoh/emacs-ipython-notebook#289] opened 2018-04-10 17:09 UTC
I have to kill emacs via shell. Only when a markdown cell is made and I edit it. 
I am using Anaconda3 for python/jupyter environment. Everything up to date
(using spacemacs report info below)

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.91
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658cd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 ansible better-defaults bibtex
 (c-c++ :variables c-c++-enable-clang-support t)
 chrome
 (clojure :variables clojure-enable-fancify-symbols t)
 command-log common-lisp coq cscope csv dash deft docker emacs-lisp erc
 (ess :variables ess-use-auto-complete t ess-use-eldoc t ess-ask-about-transfile nil)
 fasd finance git github go gpu
 (haskell :variables haskell-completion-backend 'intero)
 helm html ibuffer imenu-list ipython-notebook java
 (javascript :variables)
 (latex :variables latex-enable-folding t latex-enable-auto-fill t latex-build-command "LatexMk" latex-enable-magic t)
 lua lsp
 (markdown :variables markdown-live-preview-engine 'vmd)
 nim ocaml
 (osx :variables osx-use-option-as-meta t)
 (org :variables org-enable-github-support t org-enable-reveal-js-support t org-enable-bootstrap-support t org-startup-indented t org-startup-folded t)
 pandoc pdf-tools php
 (python :variables python-backend 'lsp)
 racket ranger
 (rust :variables rust-format-on-save t)
 (scala :variables scala-auto-insert-asterisk-in-comments t scala-enable-eldoc t scala-indent:use-javadoc-style t)
 scheme search-engine
 (spell-checking :variables spell-checking-enable-by-default nil)
 sql syntax-checking
 (shell :variables shell-default-height 30 shell-default-position 'right)
 themes-megapack tmux
 (treemacs :variables treemacs-use-follow-mode t treemacs-use-filewatch-mode t)
 vagrant version-control yaml zotero)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
Debugger is never triggered
```

**Comment by mvarela** [comment] 2018-04-11 07:47
I'm having the exact same problem (and same system/emacs configuration as @vv111y). Tried the suggestions in #273, but it doesn't help.
If there's any Markdwon cell in the notebook, it will cause a crash. 
I also reinstalled both markdown-mode and ein, to make sure they were fresh copies.

My layers are:
```
    (
     a
     sunburn-theme
     icon-line
     atomic-chrome
     csv
     python
     graphviz
     ob-ipython
     ipython-notebook
     json-navigator
     markdown
     javascript
     forecast
     html
     paren-face
     emacs-lisp
     git
     org
     org-pdfview
     pdf-tools
     shell
     major-modes
     syntax-checking
     haskell
     purescript
     scala
     elm
     ruby
     helm-pages
     clojure
     java
     themes-megapack
     erlang
     elixir
     fsharp
     personal
     ess
     c-c++
     rust
     latex
     bibtex
     common-lisp
     scheme
     dash
     (auto-completion :variables
                      auto-completion-enable-snippets-in-popup t)
     (colors :variables
             colors-enable-nyan-cat-progress-bar t
             colors-enable-rainbow-identifiers t )
     )

```

**Comment by vv111y** [comment] 2018-04-30 19:48
Ok, so far so good; using @drc-bsorenson suggestion of git clean. 

@mvarela, did all the packages get reinstalled and recompiled? That was what happened for me.

**Comment by Vvkmnn** [comment] 2018-08-12 21:25
I attempted to create a password via `jupyter notebook password`, and then tried the [`git clean -xfd`](https://github.com/millejoh/emacs-ipython-notebook/issues/273#issuecomment-368899243) suggested, but found the same issues. 

System Info 💻
* OS: macOS
* Emacs:  26.1
* Spacemacs: 0.300.0
* Spacemacs branch: develop https://github.com/syl20bnr/spacemacs/commit/6a724e416de4c3529f30edb45213a793a13cb959  
* Graphic display: t
* Distribution: spacemacs
* Editing style: vim
* Completion: ivy

Here's my Jupyter during the dump:
![image](https://user-images.githubusercontent.com/1954615/44006379-b276ebca-9e51-11e8-99d1-e5e84f769776.png)

However, changing from Spacemacs `master` to `develop` (release 204 > 300) seems to have fixed the issue. Running the same markdown cell does not yield any ugly dumps. 👍

**Comment by Vvkmnn** [comment] 2018-08-14 19:17
Nevermind, started showing up again. Trying to grab some more detail with `ein:dev-start-debug`. I'm an Emacs noob, so lemme know if there's anything I can run to shed some more context on this. 

Now it occasionally happens when I'm editing Python cells. This is what the Jupyter log looks like when it happens:
```bash
[I 15:01:33.287 NotebookApp] Saving file at /hydra.ipynb
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 431, in complete_request
    code = content['code']
KeyError: 'code'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 431, in complete_request
    code = content['code']
KeyError: 'code'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 431, in complete_request
    code = content['code']
KeyError: 'code'

...
[I 15:02:33.321 NotebookApp] Saving file at /hydra.ipynb
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 431, in complete_request
    code = content['code']
KeyError: 'code'
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 431, in complete_request
    code = content['code']
KeyError: 'code'
...
```
On and on like that until that process restarted, which somehow in turn crashes / hangs Emacs (which I restart with `killall Emacs` on macOS). 

Seems to happen on saving as well somehow, so probably more similar to https://github.com/millejoh/emacs-ipython-notebook/issues/133. I'll see what the debug gets geets me.

**Comment by millejoh** [comment] 2018-08-29 22:41
Looks like the same issue as #325, which should be fixed now. Hope that is the case! Reopen if you disagree.

**Closed by millejoh** 2018-08-29 22:41 UTC

**Comment by chep** [comment] 2019-08-12 10:39
I have the same problem. I build emacs from master (27.0.50) and have ein from melpa (ein-20190729.20).

I can't do anything when emacs is frozen. 100% cpu usage. I tried ein:dev-start-debug but there is no error and I can't interrupt with C-g.
While I'm writing this message, I can read this in the minibuffer:
>ein: [verbose] Checkpoint checkpoint mynotebook.ipynb generated.

I took me a long time to write this message (several minutes) and my emacs is
back :-) so it is not frozen forever...
Tell me if you know how I can have more debug information.

**Comment by dickmao** [comment] 2019-08-12 11:11
EIN changed a lot since Aug2018, so I would start a new issue using `M-x ein:dev-bug-report-template` as described in the README.  Adding a minimum reproducible example would raise my outlook from "mild curiosity" to "this can be fixed."

Also, we only test emacs25 and emacs26.  We don't officially support unreleased versions of emacs.
