### ISSUE TITLE
ein: [warn] Kernel is not ready yet! (or closed already.)

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#163] opened 2017-01-09 16:20 UTC
Fresh Emacs, fresh jupyter.
Logged in using `ein:notebooklist-login` - no problem.
Got the notebook list using `ein:notebooklist-open` - no problem.
Open a notebook:
```
Debugger entered--Lisp error: (websocket-received-error-http-response . 403)  
  signal(websocket-received-error-http-response 403)                          
  websocket-outer-filter(#1=[cl-struct-websocket closed #4=[cl-struct-ein:$web
  #[(process output) "\303\304\"\305        \n\")\207" [process websocket 
```
terminal:
```
[I 11:13:59.243 NotebookApp] 302 POST /login (127.0.0.1) 1.92ms
[W 11:13:59.245 NotebookApp] 405 POST / (127.0.0.1) 0.89ms referer=None
[W 11:14:17.407 NotebookApp] Notebook master-list.ipynb is not trusted
[W 11:14:18.575 NotebookApp] Sessions API changed, see updated swagger docs
[W 11:14:18.688 NotebookApp] Couldn't authenticate WebSocket connection
[W 11:14:18.693 NotebookApp] 403 GET /api/kernels/13c58512-fe18-4e84-8eb7-2a486772af69/channels?session_id=127ebba1-31f2-46ae-8391-e10a23822497 (127.0.0.1) 8.38ms referer=None
```
The buffer with the notebook _is_ shown, but `C-c C-c` there results in the warning:
```
ein: [info] Login to 8888 complete. Now you can open notebook list by `ein:notebooklist-open'.
ein: [info] Opened notebook list at 8888 with path 
ein: [info] Opening notebook master-list.ipynb...
ein: [info] Reading nbformat4 notebook.
....
ein: [info] Worksheet master-list.ipynb is ready
ein: [info] Enabling autosaves for master-list.ipynb with frequency 60 seconds.
....
ein: [info] Kernel started: 13c58512-fe18-4e84-8eb7-2a486772af69
ein: [info] Starting channels WS: "ws://127.0.0.1:8888/api/kernels/13c58512-fe18-4e84-8eb7-2a486772af69/channels?session_id=127ebba1-31f2-46ae-8391-e10a23822497"
Entering debugger...
ein: [info] Opened notebook list at 8888 with path 
...
ein: [warn] Kernel is not ready yet! (or closed already.)
```

**Comment by sam-s** [comment] 2017-01-09 16:21
`ein:notebook-reconnect-kernel` leads to `(websocket-received-error-http-response . 403)`
and 
```
[W 11:20:31.323 NotebookApp] Sessions API changed, see updated swagger docs
[W 11:20:31.346 NotebookApp] Couldn't authenticate WebSocket connection
[W 11:20:31.351 NotebookApp] 403 GET /api/kernels/13c58512-fe18-4e84-8eb7-2a486772af69/channels?session_id=127ebba1-31f2-46ae-8391-e10a23822497 (127.0.0.1) 9.72ms referer=None
```

**Comment by millejoh** [comment] 2017-01-09 20:47
What version of jupyter notebook are you running? What backend is the request package using - curl or url-request?

In the past this has happened (the 403 forbidden response) because the cookie with the authentication token wasn't getting passed to the websocket request. I've noticed some problems with url-request in recent versions of Emacs, but I haven't had time to look too closely into what is happening.

**Comment by sam-s** [comment] 2017-01-09 21:39
shell:
```$ jupyter notebook --version
4.3.0
```
emacs:
```
request-backend
==> curl
```
maybe the `Sessions API changed, see updated swagger docs` indicates a protocol change?

**Comment by millejoh** [comment] 2017-01-10 14:45
A long shot, but let me know if you adding the following advice does anything:

```elisp
(advice-add 'request--netscape-cookie-parse :around #'fix-request-netscape-cookie-parse)
```

In 4.3.0 jupyter started using HTTP_ONLY cookies for authentication, which broke request. Supposedly fixed now, but maybe the changes haven't made their way to your installation.

**Comment by clerian** [comment] 2017-01-10 15:53
Hello,
I can confirm this issue, I've got the same configuation with jupyer notebook version 4.3.0. In addition I have issues creating new notebooks from ein. The error message is  

[W 16:52:26.073 NotebookApp] Invalid JSON in body of request

I don't know if this is a related problem or not..

**Comment by UndeadKernel** [comment] 2017-01-11 09:36
I had the same issue described by the OP.
Adding the advice @millejoh suggested solved the issue.

**Comment by sam-s** [comment] 2017-01-19 15:07
I still get `Kernel is not ready yet! (or closed already.)`

**Comment by millejoh** [comment] 2017-01-19 17:34
Could you include a copy of the contents of curl's cookie jar file (should be wherever `request-storage-directory` is pointing at)?

I am unsure how informative it will be, but I'd still like to see the log from the websocket connection. Calling `ein:dev-start-debug` or `(setq websocket-debug t)` will do that. I just pushed a commit with the command `ein:dev-pop-to-debug-channels` that will automatically take you to the websocket log for the current notebook. Otherwise you'll have to hunt down the buffer yourself via the kernel id.

Note that I am not exactly sure what has changed in the sessions API, but whatever the change is it hasn't been causing problems in my setup.

Good luck.

**Comment by sam-s** [comment] 2017-01-19 18:16
I really feel stupid now.
I looked at the `~/.emacs.d/request/curl-cookie-jar` file (pointed to by `request-storage-directory`) and did not find the `token` from the `jupyter` URL, so I did `M-x ein:notebooklist-login RET RET <token>` and then `M-x ein:notebooklist-open RET RET` and then opened the notebook again and it worked (yay!!! does every `jupyter` session have a different token?)
Then I went back to `curl-cookie-jar` and reloaded the file (it was modified) and I _still_ don't see there the token (I guess it is encrypted/hashed?)
So, I guess I am a happy camper for now 👍 
Thanks!

**Comment by millejoh** [comment] 2017-01-19 22:56
This is what my cookie jar looks like:

```
# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_127.0.0.1	FALSE	/	FALSE	1485108558	username-127-0-0-1-8888	"2|1:0|10:1482516558|23:username-127-0-0-1-8888|44:MjhmZDlhM2E3NTFjNGJiNmJiYWQyYjZlOGIzMzA1MmY=|47d9461360cb49bbfff4c14814848b46abffc463dfb4851c942b679baa17cfe8"
127.0.0.1	FALSE	/	FALSE	1486082869	_xsrf	2|c4a1af42|59f8b255e6207941643b8bdbf23fa733|1483490869
localhost	FALSE	/	FALSE	0	_xsrf	2|f7a36ba4|dc57047679f774594f5b13407ed8a8c6|1484084333
#HttpOnly_127.0.0.1	FALSE	/	FALSE	1486868588	username-127-0-0-1-8889	"2|1:0|10:1484276588|23:username-127-0-0-1-8889|44:YjUwMzkyYWFiNjVlNDQ3Njk5ZDFjYjI2MmQ1YjZhYTQ=|c13272c880fca8440a389ab22680aaef8283a5e444ae0344782055d684346a44"
```

The token is one of the #HttpOnly_127.0.0.1 cookies and yes they are encrypted. Note that I have two because I was running notebook on ports 8888 and 8889. These should carry through multiple notebook sessions on the same machine, i.e. you should only have to login with the token once in a while. You shouldn't have to keep re-entering the token, though maybe something is causing the cookie to expire???

Glad at least that you can get it to work.

**Comment by PopTudor** [comment] 2017-12-23 20:28
Sorry for my lack of knowledge but I also have this issue with fresh install of Anaconda. Could any of you walk me step by step on how to run the code above? I tried the #213 fix but then I get 'Forbidden' whenever I'm trying to create a file.

Thank you! :)

**Comment by wxjeacen** [comment] 2018-03-16 16:36
Same problem, really hope can work this problem out.

**Comment by sam-s** [comment] 2018-09-04 15:52
The problem recurred.
After `ein:notebook-reconnect-kernel`, `(websocket-ready-state (ein:$websocket-ws websocket))` in `ein:websocket-open-p` called from `ein:kernel-live-p` is `connecting` instead of `open`.

**Comment by millejoh** [comment] 2018-09-07 22:58
Okay, let's see if I can recreate this one. Since it's been a while since this case has been opened, would you mind re-sending the following info?

1. Version of Jupyter (`jupyter notebook --version`) you are using.
2. How you are launching jupyter (remote or local command line, or your settings for launching via `ein:jupyter-server-start`).
3. Let me know if you have customized any settings in your `jupyter_notebook_config.py`
4. Is the kernel still active when you execute `ein:notebook-reconnect-kernel`?

I see that the code calls `ein:kernel-disconnect` prior to making a call to `ein:kernel-start`. Doing that makes sense and seems to work with a notebook that has an active connection to a running kernel, but maybe something more needs to be done if the websocket connection has become corrupted somehow.

**Comment by sam-s** [comment] 2018-09-09 04:03
1. `5.6.0`
2. `jupyter notebook --ip='*'` at the remote shell prompt
3. I don't have a `jupyter_notebook_config.py` file
4. I am not sure what you mean; I see `ein: [info] Starting channels WS: "wss://datasci-1.clearme.com:8888/` after `ein:notebook-reconnect-kernel` but `ein:worksheet-kernel-status` reports `((ein:$kernel-channels . connecting))`.

**Comment by sam-s** [comment] 2018-09-09 16:48
`ein: [info] Failed to login to https://ec2-13-58-41-203.us-east-2.compute.amazonaws.com:8888`

**Comment by millejoh** [comment] 2018-09-09 20:42
Okay, not sure if this was you but I saw this in the log:

```
[W 14:38:10.000 NotebookApp] SSL Error on 10 ('198.108.66.240', 44930): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:841)
[W 15:48:34.651 NotebookApp] SSL Error on 10 ('88.117.159.146', 49969): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:841)
[W 15:48:35.820 NotebookApp] SSL Error on 10 ('88.117.159.146', 49974): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:841)
[W 16:24:14.975 NotebookApp] SSL Error on 10 ('63.246.129.30', 50100): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:841)
```

Can you connect to my instance using the web browser? This is just to make sure I didn't mess up any settings on my end.

I'm using a self-signed certificate, so curl won't work unless it is called with the `--insecure` argument. There is also a known issue with ssl and OS X. The [wiki](https://github.com/millejoh/emacs-ipython-notebook/wiki/Tips) has some suggestions on how to handle.

**Comment by sam-s** [comment] 2018-09-09 21:16
worked fine with the browser (with scary warnings that the connection is not encrypted).
`ein: [info] Failed to login` with both `http` and `https` (at 17:16 EDT)

**Comment by millejoh** [comment] 2018-09-19 01:06
Well, my grand idea for helping seems to have done anything but. My apologies for the red herring. I unfortunately do not have a good idea of what might be happening, but I can at least explain what EIN is doing when it tries to open a websocket connection to the notebook server.

## How EIN Handles Authentication and XRSF Tokens

This assumes that `request-backend` is set to `curl`.

Once a user successfully authenticates against a running jupyter server via `ein:notebooklist-login` curl will store two cookies in the `curl-cookie-jar` file. The location of this file is set by the variable `request-storage-directory`. One cookie is for the token authentication, and the other is the xsrf token. [Below](#org667acd1) is an example of cookies that were set after authenticating against a jupyter notebook server running on my personal aws instance.

On subsequent calls to the content API request/curl will automatically supply the correct cookies, which is why you can navigate around in the notebooklist buffer and at least start the process for opening a notebook. The trick comes when trying to open a websocket connection to a running kernel.

The websocket package uses the `url` package to set cookies, and so will not know about the authentication and `xsrf` tokens unless EIN does some extra work. EIN does this in the `ein:websocket--prepare-cookies` function. The function does some extra work to only copy over cookies pertaining to the host the websocket is connecting on. I'm not sure that extra work is really necessary, but so far it's worked for me.

So, if the websocket connection is not authenticating then it is possible that EIN is not correctly copying over the authentication and xsrf tokens. You can check what cookies have been set by calling `url-cookie-list` in the notebook buffer.

Another possibility is that EIN is getting confused and cannot find the cookies it needs in the `curl-cookie-jar`. This might happen if there is some weird redirection going on for the notebook server URL's, although EIN does try to respect any HTTP redirect requests.

In any case, seeing the notebook server log messages that are generated when the websocket authentication fails would probably be useful and help narrow down the issue a bit. Enabling debugging for websocket (see the `websocket-debug` variable).

### Example curl cookie jar file<a id="sec-1"></a>

`ec2-13-58-41-203.us-east-2.compute.amazonaws.com	FALSE	/	FALSE	0	_xsrf 2|164f26da|390fef58a22a21f913024720d16e0328|1535314712`

`#HttpOnly_ec2-13-58-41-203.us-east-2.compute.amazonaws.com	FALSE	/	TRUE	1539117935	username-ec2-13-58-41-203-us-east-2-compute-amazonaws-com-8888	"2|1:0|10:1536525935|62:username-ec2-13-58-41-203-us-east-2-compute-amazonaws-com-8888|44:NmMwYzg5NDA2MDBkNDVjNzk1mMY3ZGEwMzg0ZDUwNTA=|b975a41e86cea678fd2b97be9e447254bdb109e7e04e8f72f74fe6a151812c4d"`

**Comment by sam-s** [comment] 2018-09-21 17:02
Thanks for the explanation.
For some reason, everything works ATM (version `"0.14.2"` from `elpa/ein-20180909.1451`), but I will play with `websocket-debug` when it fails again.

**Comment by sam-s** [comment] 2018-09-27 18:38
Amazingly enough, I now have two notebooks, a working one, and a broken one.
With `websocket-debug` set to `t`, the working one has a `*debug*` buffer with
```
[WS] Received: \211^@
[WS] Sending frame, opcode: pong payload: 
```
appended every few seconds and 
```
[WS] Sending frame, opcode: text payload: {"header...
```
and I send code to be executed.

The broken notebook has no `pong` frames.
It has
```
[WS] Sending handshake, key: AqiIfekrIa84keeaRoqfrQ==, acceptance: H5+J6MnZA8seYANz5UjtOpQF19M=
```
on `ein:notebook-reconnect-kernel` and, eventually,
```
[WS] State change to connection broken by remote peer
```
`url-cookie-list` shows two cookies (`_xsrf` and `username-datasci-1-c...`).

**Closed** 2020-02-01 16:34 UTC
