### ISSUE TITLE
ein: [error] Kernelspc query call failed with status parse-error

### ISSUE THREAD

**Issue by mashu** [millejoh/emacs-ipython-notebook#306] opened 2018-05-23 19:37 UTC
Using
```
GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-05-07, modified by Debian
and
ein 20180520.642
```

Steps
```
M-x ein:notebooklist-open <paste url>
```

Error
`ein: [error] Kernelspc query call failed with status error.`

**Comment by millejoh** [comment] 2018-05-28 13:53
What is the output from the running jupyter server? What exactly does the pasted url look like?

**Comment by maliky** [comment] 2018-05-29 20:06
I have the same error, after an ein update to `ein-20180526.732 `
I'm using `GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9)  of 2017-09-20 on lcy01-07, modified by Debian`

Steps (showing the *Messages* buffer)
- `M-x ein:jupyter-server-start `
```
Eager macro-expansion failure: (void-function custom-variable-type)
Starting notebook server in directory: ~/Prog/Python/
ein: [info] Login to http://localhost:8888 complete. Now you can open notebook list by `ein:notebooklist-open'.
Blocking call to accept-process-output with quit inhibited!! [2 times]
Mark set
```
The eager macro-expansion failure is already strange
But I continue and run:
- `ein:notebooklist-open`
```
ein: [error] Kernelspc query call failed with status error.
ein: [error] Content list call http://127.0.0.1:8888/api/contents/ failed with status error.

```
 And the resulting *ein:jupyter-server* buffer
```
[I 20:02:14.814 NotebookApp] JupyterLab beta preview extension loaded from /home/mlk/.local/share/virtualenvs/Python--sNkv1kf/lib/python3.5/site-packages/jupyterlab
[I 20:02:14.814 NotebookApp] JupyterLab application directory is /home/user/.local/share/virtualenvs/Python--sNkv1kf/share/jupyter/lab
[I 20:02:14.818 NotebookApp] Serving notebooks from local directory: /home/user/Prog/Python
[I 20:02:14.818 NotebookApp] 0 active kernels
[I 20:02:14.819 NotebookApp] The Jupyter Notebook is running at:
[I 20:02:14.819 NotebookApp] http://localhost:8888/?token=242a27b7f7a6d58ccdcbdf69e127a26bf93499e43376d07f
[I 20:02:14.819 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 20:02:14.819 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=242a27b7f7a6d58ccdcbdf69e127a26bf93499e43376d07f&token=242a27b7f7a6d58ccdcbdf69e127a26bf93499e43376d07f
[I 20:02:26.750 NotebookApp] 302 POST /login (127.0.0.1) 2.90ms
[W 20:02:26.751 NotebookApp] 405 POST / (127.0.0.1) 0.58ms referer=None
[W 20:03:00.723 NotebookApp] Forbidden
[W 20:03:00.724 NotebookApp] 403 GET /api/kernelspecs (127.0.0.1) 2.77ms referer=None
[W 20:03:00.743 NotebookApp] Forbidden
[W 20:03:00.744 NotebookApp] 403 GET /api/contents/ (127.0.0.1) 1.25ms referer=None
```

I can run notebooks from the navigator.

What I am expecting is the opening of the buffer *ein:notebooklist http://localhost:8888* with my notebooks.

Instead I have to manualy open *ein:notebooklist http://localhost:8888* and it's a text buffer with no notebooks.

**Comment by maliky** [comment] 2018-05-30 16:37
I've updated emacs to `GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.18.9)  of 2018-05-29` and reduced my `init.el` to this few lines:

[minimal .emacs.d/init.el](https://gist.github.com/maliky/d8287a4125f2b2f2a26a92d9dca318cd)

But still ein-20180526.732/ is giving me the following errors in  *Messages*

```
For information about GNU Emacs and the GNU system, type C-h C-a.
Eager macro-expansion failure: (void-function custom-variable-type)
Starting notebook server in directory: ~/Prog/Python/
Making completion list...
Mark set
ein: [info] Login to http://localhost:8888 complete. Now you can open notebook list by `ein:notebooklist-open'.
Blocking call to accept-process-output with quit inhibited!! [2 times]
Mark set
```

and here in  *ein:jupyter-server*
```
[I 16:24:38.125 NotebookApp] JupyterLab beta preview extension loaded from /home/user/.local/share/virtualenvs/Python--sNkv1kf/lib/python3.5/site-packages/jupyterlab
[I 16:24:38.125 NotebookApp] JupyterLab application directory is /home/user/.local/share/virtualenvs/Python--sNkv1kf/share/jupyter/lab
[I 16:24:38.131 NotebookApp] Serving notebooks from local directory: /home/user/Prog/Python
[I 16:24:38.131 NotebookApp] 0 active kernels
[I 16:24:38.131 NotebookApp] The Jupyter Notebook is running at:
[I 16:24:38.131 NotebookApp] http://localhost:8888/?token=46ad98a2e5287a21cf57a44f97b4f44d3ac49f29d0b51ac1
[I 16:24:38.131 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:24:38.131 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=46ad98a2e5287a21cf57a44f97b4f44d3ac49f29d0b51ac1&token=46ad98a2e5287a21cf57a44f97b4f44d3ac49f29d0b51ac1
[I 16:24:49.787 NotebookApp] 302 POST /login (127.0.0.1) 2.99ms
[W 16:24:49.790 NotebookApp] 405 POST / (127.0.0.1) 1.24ms referer=None
```

All works as expected in  the navigator but in emacs I just get a text buffer.

**Comment by millejoh** [comment] 2018-05-31 12:29
And this is the exact error that travis has been throwing for the past month or so and which I have been unable to reproduce. It started sometime after I pushed out v0.14.1. I think if you download from MELPA stable or grab this version you should at least have a version of ein that works while I figure out what is going on.

**Comment by millejoh** [comment] 2018-05-31 18:23
I understand what is causing the eager macro expansion error and it should be fixed in the most recent commit. My fingers are crossed that this will also fix the other issues you see with opening the notebooklist and individual notebooks.

MELPA should be updating in a bit; give it an hour or four before you try to update and let me know if it works!

**Comment by maliky** [comment] 2018-05-31 23:16
I down graded to ein 0.14.1 but the problem continued until I change my jupyter exec from my pipenv jupyter to the system jupyter.
Could it be a path issue ?

with below does not work (jupyter version 4.4.0, python 3.5.2)
```
(setq ein:jupyter-default-server-command "/home/user/.local/share/virtualenvs/Python--sNkv1kf/bin/jupyter")
```
with below works (version 4.4.0, python 2.7.12)
```
 (setq ein:jupyter-default-server-command "/usr/local/bin/jupyter")
```


Oh well.. 
I've upgraded back to `ein 20180531.1115` and now.  Thank you very much...
Your piece of software makes me love emacs a bit more every day.

**Comment by millejoh** [comment] 2018-06-01 12:46
Thank you!

It's possible this particular bug went back even furthe than I thought. From the jupyter server log it looks like ein is successfully sending the initial login request, but there is no followup request to get the contents of the root directory on the server. This may be because of an error that was keeping the necessary code from getting loaded.

If this happens again please call `M-x ein:dev-start-debug` before starting and connecting to the jupyter server and then send the contents of the `*ein:log-all*` buffer.

**Comment by jonathan-lin** [comment] 2018-08-02 06:46
I am having a similar issue. I'm running emacs 25.3.1 on Windows 10 and I installed EIN from MELPA. When I run `ein:jupyuter-server-start` a browser window pops open with a working Jupyter notebook interface. However, emacs throws these errors: 
```Starting notebook server in directory: c:/Users/Jon/Documents/emacs-25.3_1-x86_64/bin/
ein: [info] Failed to login to http://localhost:8888
ein: [error] Kernelspc query call failed with status error.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Error (error) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Error (error) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Error (error) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Error (error) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Error (error) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Error (error) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Error (error) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Error (error) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Error (error) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Error (error) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Error (error) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Error (error) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Error (error) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Error (error) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Error (error) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Error (error) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Error (error) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [39 times]
REQUEST [error] Callback is not called when stopping process! Explicitly calling from timer.
REQUEST [error] Error (timeout) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Callback is not called when stopping process! Explicitly calling from timer.
REQUEST [error] Error (timeout) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Callback is not called when stopping process! Explicitly calling from timer.
REQUEST [error] Error (timeout) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Callback is not called when stopping process! Explicitly calling from timer.
REQUEST [error] Error (timeout) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [4 times]
REQUEST [error] Callback is not called when stopping process! Explicitly calling from timer.
REQUEST [error] Error (timeout) while connecting to http://localhost:8888/api.
REQUEST [error] Callback is not called when stopping process! Explicitly calling from timer.
REQUEST [error] Error (timeout) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Callback is not called when stopping process! Explicitly calling from timer.
REQUEST [error] Error (timeout) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Callback is not called when stopping process! Explicitly calling from timer.
REQUEST [error] Error (timeout) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!! [2 times]
REQUEST [error] Callback is not called when stopping process! Explicitly calling from timer.
REQUEST [error] Error (timeout) while connecting to http://localhost:8888/api.
Blocking call to accept-process-output with quit inhibited!!
Error (wrong-type-argument number-or-marker-p nil) on query contents, try calling ‘ein:notebooklist-login‘ first...
REQUEST [error] Error (error) while connecting to http://localhost:8888/api. [19 times]
REQUEST [error] Error (timeout) while connecting to http://localhost:8888/api. [9 times]```

The server log only shows the browser logging in:

```
[I 23:44:54.592 NotebookApp] Serving notebooks from local directory: c:\Users\Jon\Documents\emacs-25.3_1-x86_64\bin
[I 23:44:54.592 NotebookApp] The Jupyter Notebook is running at:
[I 23:44:54.593 NotebookApp] http://localhost:8888/?token=845f67c2f06279e6c0ff62a1f1c8b14069a9b7597b893c61
[I 23:44:54.593 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 23:44:54.610 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=845f67c2f06279e6c0ff62a1f1c8b14069a9b7597b893c61
[I 23:44:55.617 NotebookApp] Accepting one-time-token-authenticated connection from ::1
```

Any thoughts?

**Closed** 2018-08-29 21:15 UTC
