### ISSUE TITLE
Can not open files in the notebooklist

### ISSUE THREAD

**Issue by jdevoto** [millejoh/emacs-ipython-notebook#238] opened 2017-09-30 14:20 UTC
I can read the notebook list, but when I try to open a notebook I get

Buffer is read-only: #<buffer *ein:notebooklist http://127.0.0.1:8888*>

I am using emacs 25 and the last version of Jupyter.

Any help is welcomed

**Comment by nwieder** [comment] 2017-09-30 19:08
I also have a strange issue related to the notebook list. After I login and open the notebook list, I don't see any directories and the buffer is not interactive. Meaning i can edit the buffer as if it was a text buffer. I do not get any error messages.

I haven't used ein in a week or so, so I'm not sure weather it's related to the last update or not...

- GNU Emacs 25.2.1 (x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G1421)) of 2017-04-24
- jupyter 4.3.0
- latest ein (20170922.1231)

**Comment by millejoh** [comment] 2017-10-02 18:50
@nwieder, that error is probably because I introduced an additional dependency to dash. I must have forgotten to add an appropriate require in the code. I think a recent pull request fixes that oversight; if not I will try to fix it myself in a bit.

Certainly, if EIN errors before the code setting up the notebooklist buffer can finish you will be left in a precarious state where none of the widgets will work.

**Comment by nwieder** [comment] 2017-10-08 21:46
Thanks @millejoh, the problem is fixed on my side...

**Closed** 2019-03-19 14:54 UTC
